In [1]:
# import numpy
import numpy as np

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.arange(4)

array([0, 1, 2, 3])

In [18]:
np.arange(3,7)

array([3, 4, 5, 6])

In [19]:
np.arange(3,7,1.5)

array([3. , 4.5, 6. ])

In [20]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
np.empty((4,2))

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 8.69555537e-321],
       [8.70018274e-313, 1.24610723e-306]])

In [24]:
np.empty((4,2), dtype=int)

array([[      0,       1],
       [      0, 5570652],
       [   1276,       0],
       [    768,      83]])

In [25]:
np.empty([4,2], dtype=int)

array([[4128860, 6029375],
       [3801155, 5570652],
       [6619251, 7536754],
       [      0,     443]])

In [27]:
np_arange = np.arange(15)
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
np_arange.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
np.linspace(1,10, num=2)

array([ 1., 10.])

In [31]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [32]:
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [35]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [39]:
deg = np.array([0,30,45,60,90])

In [36]:
np.pi

3.141592653589793

In [37]:
np.pi/180

0.017453292519943295

In [40]:
deg*np.pi/180

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [41]:
np.sin(deg*np.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])