# Scipy - Linear algebra

In [42]:
import numpy as np
from scipy import linalg

## problem statement

- Test has 30 questions for total of 150 marks
- There are x - number of true or false questions
- there are y - number of multiple choice questions
- x + y = 30
- 4x + 9y = 150
- the marks for x question is 4, y question is 9
- the problem is to find the x and y 
- solve the linear algebra equations using solve method of linalg package of scipy

In [43]:
question_variables = np.array([[1,1],[4,9]])
question_values = np.array([30,150])

In [44]:
question_variables

array([[1, 1],
       [4, 9]])

In [45]:
question_values

array([ 30, 150])

In [48]:
linalg.solve(question_variables,question_values)

array([24.,  6.])

- x = number of true/false questions are 24
- y = number of multiple choice questions are 6